name: provider_mvc
description: Flutter Provider MVC Implementation that make state management easier.
version: 3.0.0
homepage: https://github.com/aymentoumi/ProviderMVC

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

